basePath: /msapi/user
host: localhost:3000
info:
  contact:
    email: ortelius-dev@googlegroups.com
    name: Ortelius Google Group
  description: |-
    RestAPI for the User Object
    ![Release](https://img.shields.io/github/v/release/ortelius/scec-user?sort=semver)
    ![license](https://img.shields.io/github/license/ortelius/scec-user)

    ![Build](https://img.shields.io/github/actions/workflow/status/ortelius/scec-user/build-push-chart.yml)
    [![MegaLinter](https://github.com/ortelius/scec-user/workflows/MegaLinter/badge.svg?branch=main)](https://github.com/ortelius/scec-user/actions?query=workflow%3AMegaLinter+branch%3Amain)
    ![CodeQL](https://github.com/ortelius/scec-user/workflows/CodeQL/badge.svg)
    [![OpenSSF-Scorecard](https://api.securityscorecards.dev/projects/github.com/ortelius/scec-user/badge)](https://api.securityscorecards.dev/projects/github.com/ortelius/scec-user)

    ![Discord](https://img.shields.io/discord/722468819091849316)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ortelius v11 User Microservice
  version: 11.0.0
paths:
  /msapi/user:
    get:
      consumes:
        - "*/*"
      description: Get a list ofthe user.
      produces:
        - application/json
      responses:
        "200":
          description: OK
      summary: Get a List of Users
      tags:
        - user
    post:
      consumes:
        - application/json
      description: Create a new User and persist it
      produces:
        - application/json
      responses:
        "200":
          description: OK
      summary: Create a User
      tags:
        - user
  /msapi/user/:key:
    get:
      consumes:
        - "*/*"
      description: Get a user based on the _key or name.
      produces:
        - application/json
      responses:
        "200":
          description: OK
      summary: Get a User
      tags:
        - user
swagger: "2.0"
